import { NodePgDatabase, memoryItems, eq, and } from '@continuum/db';
import { SecurityContext, PolicyEngine } from '@continuum/security';

export class ProjectBriefGenerator {
  constructor(private db: NodePgDatabase<any>) {}

  async generateBrief(ctx: SecurityContext, projectId: string): Promise<string> {
    PolicyEngine.assert(ctx, { action: 'read', resourceType: 'project', projectId });

    const items = await this.db.select()
      .from(memoryItems)
      .where(and(
        eq(memoryItems.projectId, projectId),
        eq(memoryItems.status, 'active')
      ));

    // Group items by type
    const decisions = items.filter((i: any) => i.type === 'decision');
    const conventions = items.filter((i: any) => i.type === 'convention');
    const constraints = items.filter((i: any) => i.type === 'constraint');
    const preferences = items.filter((i: any) => i.type === 'preference');

    let brief = `# Project Context Brief\n\n`;
    brief += `> Generated by Continuum\n\n`;

    if (decisions.length > 0) {
      brief += `## Architecture & Decisions\n`;
      decisions.forEach((d: any) => {
        brief += `- ${d.content}\n`;
      });
      brief += `\n`;
    }

    if (conventions.length > 0) {
      brief += `## Conventions\n`;
      conventions.forEach((c: any) => {
        brief += `- ${c.content}\n`;
      });
      brief += `\n`;
    }

    if (constraints.length > 0) {
      brief += `## Constraints\n`;
      constraints.forEach((c: any) => {
        brief += `- ${c.content}\n`;
      });
      brief += `\n`;
    }

    if (preferences.length > 0) {
      brief += `## Preferences\n`;
      preferences.forEach((p: any) => {
        brief += `- ${p.content}\n`;
      });
      brief += `\n`;
    }

    if (items.length === 0) {
      brief += `No specific context rules found for this project.\n`;
    }

    return brief.trim();
  }
}
